export const GETPROVINCE='GETPROVINCE'

export const GETCITY='GETCITY'

export const LOGINSTATUS='LOGINSTATUS'

export const SAVEUSERINFO='SAVEUSERINFO'


export const GOTOUSERINFO='GOTOUSERINFO'

export const SAVECARNO='SAVECARNO'

export const SAVESCHEM='SAVESCHEM'

export const SAVEADDRESS='SAVEADDRESS'

export const SAVECHOICETYPE='SAVECHOICETYPE'

export const UPDATETYPE='UPDATETYPE'

//微信公众号
export const SET_WX_JS_URL='SET_WX_JS_URL'

export const UPDATE_LOADING_STATUS='UPDATE_LOADING_STATUS'

export const UPDATE_DEVICE='UPDATE_DEVICE'

